name: Deploy Uber-Lite to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Build & Push to Docker Hub | JOB name build and push  and their steps
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/uber-backend:latest

    - name: Build and Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/uber-frontend:latest

  # JOB 2: deply and its steps  - ive added 2 steps in it, 1st step copy docker compose file in ec2 (that will pull our uploaded code from docker)
  deploy:
    needs: build-and-push #its a check if will push afer job 1 is successful
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code  #checkout code because will copy our docker-compose-prod.ym file
      uses: actions/checkout@v3

    
    - name: Copy Docker Compose to EC2  #copying docker file in ec2, login ec2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.prod.yml"
        target: "/home/ubuntu"

    # Connect and Execute with Environment Variables
    - name: Bootstrap and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo " Starting Deployment..."

          # 1. EXPORT VARIABLE
          # This makes the username available to the shell
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

          # 2. AUTO-INSTALL DOCKER
          if ! command -v docker &> /dev/null
          then
              echo " Docker not found! Installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
          fi

          # 3. DEPLOYMENT
          echo " Updating Containers..."
          
          # Login on our docker repo so we can pull it from our docker the images (doing login from ec2 because incase our docker repo is private)
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          # Stop old version (Using -E to pass our exported DOCKER_USERNAME to sudo)
          sudo -E docker-compose -f docker-compose.prod.yml down

          # Download new version
          sudo -E docker-compose -f docker-compose.prod.yml pull

          # Start new version
          sudo -E docker-compose -f docker-compose.prod.yml up -d

          # Cleanup
          sudo docker image prune -f

          echo "ðŸŽ‰ App is Live!"