name: Deploy Uber-Lite to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Build & Push to Docker Hub | JOB name build and push  and their steps
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/uber-backend:latest

    - name: Build and Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/uber-frontend:latest

  # JOB 2: deply and its steps
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # NOTE: We removed the 'sed' step. We just copy the file as-is now.
    - name: Copy Docker Compose to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.prod.yml"
        target: "/home/ubuntu"

    # Connect and Execute with Environment Variables
    - name: Bootstrap and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "üöÄ Starting Deployment..."

          # 1. EXPORT VARIABLE (Crucial Fix)
          # This makes the username available to the shell
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

          # 2. AUTO-INSTALL DOCKER
          if ! command -v docker &> /dev/null
          then
              echo "‚ö†Ô∏è Docker not found! Installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
          fi

          # 3. DEPLOYMENT
          echo "üîÑ Updating Containers..."
          
          # Login
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          # Stop old version (Use -E to pass our exported DOCKER_USERNAME to sudo)
          sudo -E docker-compose -f docker-compose.prod.yml down

          # Download new version
          sudo -E docker-compose -f docker-compose.prod.yml pull

          # Start new version
          sudo -E docker-compose -f docker-compose.prod.yml up -d

          # Cleanup
          sudo docker image prune -f

          echo "üéâ App is Live!"